#!/bin/sh
#scaf->scafo compiler

if [ -z "$1" ]; then
	echo
	echo "scaf rules compiler"
	echo "usage:"
	echo "    scafc source [dest]"
	echo
	exit 0
fi

if [ -z "$2" ]; then
	DEST=$1o
else
	DEST=$2
fi

if ! test -f $1
then
	echo "source module $1 not found."
	exit 1
fi

SCAFDIR=`dirname $0`
if ! test -f $SCAFDIR/scafc.pl;
then
	SCAFDIR=`dirname $SCAFDIR`
	SCAFDIR="$SCAFDIR/lib/scaf"
	if ! test -f $SCAFDIR/scafc.pl
	then
		echo "scaf library not found in $SCAFDIR"
		exit 1
	fi
fi

TMP_S=`tempfile -s .S`
$SCAFDIR/scafc.pl -I$SCAFDIR $1 > $TMP_S \
&& cat $TMP_S \
&& gcc -x assembler-with-cpp -I$SCAFDIR -shared -o $DEST $TMP_S \
&& strip --strip-unneeded $DEST \
&& rm $TMP_S \
|| exit 1
